version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: wishlist-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - wishlist-network

  mongo-express:
    image: mongo-express
    container_name: wishlist-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
    networks:
      - wishlist-network

  wishlist-api:
    build: .
    container_name: wishlist-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/admin
    depends_on:
      - mongo
    networks:
      - wishlist-network

volumes:
  mongo-data:

networks:
  wishlist-network:
    driver: bridge
